version: '3.1'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./src:/var/www/html/
    command: php -S 0.0.0.0:8080 -t /var/www/html/